In [24]:
import numpy as np
from ch01.bandit import Bandit

bandit = Bandit()
Qs = np.zeros(10)
ns = np.zeros(10)

for n in range(300):
    action = np.random.randint(0, 10)  # ランダムな行動をする
    reward = bandit.play(action)

    ns[action] += 1
    Qs[action] += (reward - Qs[action]) / ns[action]
    print(Qs)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 0. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0. 0. 0. 1. 0. 0. 1. 0. 1. 1.]
[0.33333333 0.         0.         1.         0.         0.
 1.         0.         1.         1.        ]
[0.33333333 0.         0.         1.         0.         0.
 1.         0.         1.         1.        ]
[0.33333333 0.         0.         1.         0.         0.
 0.66666667 0.         1.         1.        ]
[0.33333333 0.         0.         1.         0.         0.
 0.75       0.    